In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[28, 90],
       [31,  9],
       [75, 18],
       [25, 40],
       [91, 24],
       [ 3, 84],
       [69, 37],
       [59, 89],
       [26, 85],
       [21,  0]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/home/silveira/anaconda3/envs/tfdl_env.yml/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[0.28409091, 1.        ],
       [0.31818182, 0.1       ],
       [0.81818182, 0.2       ],
       [0.25      , 0.44444444],
       [1.        , 0.26666667],
       [0.        , 0.93333333],
       [0.75      , 0.41111111],
       [0.63636364, 0.98888889],
       [0.26136364, 0.94444444],
       [0.20454545, 0.        ]])

In [9]:
scaler_model.fit_transform(data)

/home/silveira/anaconda3/envs/tfdl_env.yml/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.28409091, 1.        ],
       [0.31818182, 0.1       ],
       [0.81818182, 0.2       ],
       [0.25      , 0.44444444],
       [1.        , 0.26666667],
       [0.        , 0.93333333],
       [0.75      , 0.41111111],
       [0.63636364, 0.98888889],
       [0.26136364, 0.94444444],
       [0.20454545, 0.        ]])

In [17]:
import pandas as pd

In [18]:
mydata=np.random.randint(0,101,(50,4))

In [19]:
mydata

array([[ 31, 100,  78,   6],
       [  5,  70,  48,  37],
       [ 98,  10,  93,  41],
       [ 75,  49,  46,  95],
       [ 77,  88,   8,  13],
       [  0,  71,  47,   3],
       [ 90,  50,  67,   9],
       [ 64,   7,  45,  10],
       [ 37,  78,  55,  36],
       [ 62,  14,  52,   9],
       [ 76,  97,  30,  53],
       [ 15, 100,  81,  77],
       [ 60,  25,  34,  27],
       [ 73,  34,  86,  75],
       [ 65,  40,  88,  31],
       [ 41,  56,  28,  98],
       [  4,  23,  62,  73],
       [ 16,  22,  34,  98],
       [ 64,  29,  83,  48],
       [ 80,  39,  75,  95],
       [  0,  15,  27,  17],
       [ 26,  98, 100,  52],
       [ 84,  57,  11,  81],
       [ 68,  25,  87,  63],
       [ 15,  73,  54,  20],
       [ 32,  50,  71,   7],
       [ 99,  23,  80,   6],
       [ 86,  68,  11,  97],
       [ 56,  24,  24,  43],
       [ 63,  80,  27,  51],
       [ 58,  87,  57,  73],
       [ 70,  57,  72,   8],
       [ 66,  23,  32,  74],
       [ 39,   2,  99,  43],
       [ 50,  

In [22]:
df = pd.DataFrame(data=mydata)

In [23]:
df

0    1    2   3
0   31  100   78   6
1    5   70   48  37
2   98   10   93  41
3   75   49   46  95
4   77   88    8  13
5    0   71   47   3
6   90   50   67   9
7   64    7   45  10
8   37   78   55  36
9   62   14   52   9
10  76   97   30  53
11  15  100   81  77
12  60   25   34  27
13  73   34   86  75
14  65   40   88  31
15  41   56   28  98
16   4   23   62  73
17  16   22   34  98
18  64   29   83  48
19  80   39   75  95
20   0   15   27  17
21  26   98  100  52
22  84   57   11  81
23  68   25   87  63
24  15   73   54  20
25  32   50   71   7
26  99   23   80   6
27  86   68   11  97
28  56   24   24  43
29  63   80   27  51
30  58   87   57  73
31  70   57   72   8
32  66   23   32  74
33  39    2   99  43
34  50   25   72  52
35  88   57   81  29
36  31   79   49  34
37  28   39   49  56
38  76   82   92  68
39  30   97   69  29
40  40   38   18  98
41  32   32   28  10
42  27   83   77  85
43  25    0   49  44
44  51   25   26  49
45  61   78   93  48
46   6    8   77  56
47  56   20   92  41
48  68   55   20   1
49  77   96   78  88

In [24]:
df = pd.DataFrame(data=mydata, columns=['f1','f2','f3','label'])

In [25]:
df

f1   f2   f3  label
0   31  100   78      6
1    5   70   48     37
2   98   10   93     41
3   75   49   46     95
4   77   88    8     13
5    0   71   47      3
6   90   50   67      9
7   64    7   45     10
8   37   78   55     36
9   62   14   52      9
10  76   97   30     53
11  15  100   81     77
12  60   25   34     27
13  73   34   86     75
14  65   40   88     31
15  41   56   28     98
16   4   23   62     73
17  16   22   34     98
18  64   29   83     48
19  80   39   75     95
20   0   15   27     17
21  26   98  100     52
22  84   57   11     81
23  68   25   87     63
24  15   73   54     20
25  32   50   71      7
26  99   23   80      6
27  86   68   11     97
28  56   24   24     43
29  63   80   27     51
30  58   87   57     73
31  70   57   72      8
32  66   23   32     74
33  39    2   99     43
34  50   25   72     52
35  88   57   81     29
36  31   79   49     34
37  28   39   49     56
38  76   82   92     68
39  30   97   69     29
40  40   38   18     98
41  32   32   28     10
42  27   83   77     85
43  25    0   49     44
44  51   25   26     49
45  61   78   93     48
46   6    8   77     56
47  56   20   92     41
48  68   55   20      1
49  77   96   78     88

In [26]:
X = df[['f1','f2','f3']]

In [27]:
X

f1   f2   f3
0   31  100   78
1    5   70   48
2   98   10   93
3   75   49   46
4   77   88    8
5    0   71   47
6   90   50   67
7   64    7   45
8   37   78   55
9   62   14   52
10  76   97   30
11  15  100   81
12  60   25   34
13  73   34   86
14  65   40   88
15  41   56   28
16   4   23   62
17  16   22   34
18  64   29   83
19  80   39   75
20   0   15   27
21  26   98  100
22  84   57   11
23  68   25   87
24  15   73   54
25  32   50   71
26  99   23   80
27  86   68   11
28  56   24   24
29  63   80   27
30  58   87   57
31  70   57   72
32  66   23   32
33  39    2   99
34  50   25   72
35  88   57   81
36  31   79   49
37  28   39   49
38  76   82   92
39  30   97   69
40  40   38   18
41  32   32   28
42  27   83   77
43  25    0   49
44  51   25   26
45  61   78   93
46   6    8   77
47  56   20   92
48  68   55   20
49  77   96   78

In [28]:
y = df['label']

In [29]:
y

0      6
1     37
2     41
3     95
4     13
5      3
6      9
7     10
8     36
9      9
10    53
11    77
12    27
13    75
14    31
15    98
16    73
17    98
18    48
19    95
20    17
21    52
22    81
23    63
24    20
25     7
26     6
27    97
28    43
29    51
30    73
31     8
32    74
33    43
34    52
35    29
36    34
37    56
38    68
39    29
40    98
41    10
42    85
43    44
44    49
45    48
46    56
47    41
48     1
49    88
Name: label, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [33]:
X_train.shape

(33, 3)

In [34]:
X_test.shape

(17, 3)